language: ruby
rvm:
  - 2.3.7

install: gem install jekyll -v 3.8.5 && gem install s3_website && gem install jekyll-feed -v 0.12.1
script: jekyll build

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "aws:s3:::javahippie.net"
  skip_cleanup: false
  local_dir: _site
  on:
    branch: master
