language: ruby
rvm:
  - 2.7.0

install: gem install s3_website
script: 
  - bundle install 
  - bundle exec jekyll build 
  - mkdir _site/about 
  - mv about.html _site/about/index.html 
  - mkdir _site/contact 
  - mv contact.html _site/contact/index.html

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "javahippie-net"
  skip_cleanup: true
  local_dir: ./_site
  on:
    branch: master
