version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build
          command: bundle bundle exec jekyll build
      - run:
          name: Proof
          command: bundle exec htmlproofer ./_site --check-html --disable-external

