version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          key: ruby-cache-{{checksum "Gemfile"}}
      - run:
          name: Build
          command: bundle exec jekyll build
      - run:
          name: Proof
          command: bundle exec htmlproofer ./_site --check-html --disable-external  --allow_hash_href
      - aws-s3/sync:
          from: ./_site
          to: 's3://javahippie-net'
